org.gradle.jvmargs=-Xmx4096M
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
android.overridePathCheck=true
# kotlin.jvm.target=1.8
org.gradle.daemon=false
android.overrideSdkCheck=true
kotlin.jvm.target.validation.mode=IGNORE
android.enableR8.fullMode=false
android.ndkVersion=26.3.11579264
