// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbeOvU5nkgLkYCc8CFMnlrK5duMQySKf0',
    appId: '1:298839588168:android:c2e4c7cfc00d90b1a1c77d',
    messagingSenderId: '298839588168',
    projectId: 'ayurease-healthcare',
    storageBucket: 'ayurease-healthcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRFoJtWef6g36IsH15uLz89IX5kW7Z2KI',
    appId: '1:298839588168:ios:fc0fb6cc396f97aea1c77d',
    messagingSenderId: '298839588168',
    projectId: 'ayurease-healthcare',
    storageBucket: 'ayurease-healthcare.firebasestorage.app',
    androidClientId:
        '298839588168-h1iiiu1396ltg1oa8hq229hiuj5rf3n6.apps.googleusercontent.com',
    iosClientId:
        '298839588168-hushpnva1pukg3s4ffprl09ieth8rco3.apps.googleusercontent.com',
    iosBundleId: 'app.ayureze.patient',
  );
}
